events {}

http {

    server {

        listen 80;

        # telemetry-ingestion-service
        location /telemetry/ {
            proxy_pass http://telemetry-ingestion-service:8000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # query-monitoring-service
        location /query/ {
            proxy_pass http://query-monitoring-service:8000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # digital-twin-service
        location /twins/ {
            proxy_pass http://digital-twin-integration-service:8000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

    }

}