host=localhost
port=80
protocol=http

max_response_ms=5000

ing_valid_threads=5
ing_valid_ramp=20
ing_valid_loops=20

backlog_camas_threads=5
backlog_camas_ramp=1
backlog_lecturas_por_cama=180
backlog_inter_request_ms=0
backlog_nodo_id=1
backlog_tipo_variable_id=1

qry_summary_threads=5
qry_summary_ramp=20
qry_summary_loops=20

qry_historico_threads=5
qry_historico_ramp=20
qry_historico_loops=20

twin_overview_threads=3
twin_overview_ramp=15
twin_overview_loops=20

twin_list_threads=3
twin_list_ramp=15
twin_list_loops=20
