host=localhost
port=80
protocol=http

max_response_ms=5000

ing_valid_threads=80
ing_valid_ramp=120
ing_valid_loops=300

backlog_camas_threads=50
backlog_camas_ramp=10
backlog_lecturas_por_cama=180
backlog_inter_request_ms=0
backlog_nodo_id=1
backlog_tipo_variable_id=1

qry_summary_threads=70
qry_summary_ramp=120
qry_summary_loops=300

qry_historico_threads=70
qry_historico_ramp=120
qry_historico_loops=300

twin_overview_threads=50
twin_overview_ramp=120
twin_overview_loops=300

twin_list_threads=50
twin_list_ramp=120
twin_list_loops=300
