host=localhost
port=80
protocol=http

max_response_ms=5000

ing_valid_threads=15
ing_valid_ramp=30
ing_valid_loops=180

ing_valid_csv=performance-tests/jmeter/data/ingestion_valid_15_camas.csv

telemetry_seed_rows=15
telemetry_reads_per_bed=180
telemetry_beds=15
